# example netlify.toml
[build]
  command = "npx prisma generate && npm run build"
  publish = ".next"

[build.environment]
  NEXTAUTH_SECRET = "temply-secret-key-for-local-dev-12345"
  NEXTAUTH_URL = "https://effulgent-unicorn-32cd31.netlify.app"
  DATABASE_URL = "postgresql://postgres:FV%3FFgA96%247%40eWTf@db.qjiztunfjlcrqcmsnowc.supabase.co:5432/postgres"

[functions]
  included_files = ["prisma/dev.db"]

  ## Uncomment to use this redirect for Single Page Applications like create-react-app.
  ## Not needed for static site generators.
  #[[redirects]]
  #  from = "/*"
  #  to = "/index.html"
  #  status = 200

  ## (optional) Settings for Netlify Dev
  ## https://github.com/netlify/cli/blob/main/docs/netlify-dev.md#project-detection
  #[dev]
  #  command = "yarn start" # Command to start your dev server
  #  port = 3000 # Port that the dev server will be listening on
  #  publish = "dist" # Folder with the static content for _redirect file

  ## more info on configuring this file: https://ntl.fyi/file-based-build-config
